# conda
name: venvOsee
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.9
  - pip
  - pip:
    - pip-tools
    - ipynb==0.5.1
  - pandas=1.2.2
  - numpy==1.19.2
  - ipykernel
  - gdal=3.2.2
  - fiona=1.8.19
  - geopandas==0.9.0
  - nbformat
